from enum import Enum

class EventType(Enum):
    NONE = 0
    ARRIVAL_SYSTEM = 1
    ARRIVAL_STATION_1 = 2
    ARRIVAL_STATION_2 = 3
    ARRIVAL_STATION_3 = 4
    DEPARTURE_STATION_1_FAST = 5
    DEPARTURE_STATION_1_SLOW = 6
    DEPARTURE_STATION_2_FAST = 7
    DEPARTURE_STATION_2_SLOW = 8
    DEPARTURE_STATION_3_FAST = 9
    DEPARTURE_STATION_3_SLOW = 10 